name: Docker CD
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: docker/build-push-action@v1
      name: Build and push the Docker image
      with:
        username: ${{ github.repository_owner }}
        password: ${{ github.token }}
        registry: docker.pkg.github.com
        repository: ${{github.repository}}
        tag_with_ref: true
        tag_with_sha: true
